const data = {
   "count":5606,
   "next":"http://backend.offbeat.today/news-v2/?format=json&page=2",
   "previous":null,
   "results":[
      {
         "id":5820,
         "headline":"Tupelo man builds jigsaw puzzles to improve his memory",
         "time":"2021-01-10T00:00:00Z",
         "body":"Alan ODonnell has put together almost 100 puzzles ranging from 300 to 1,000 pieces each. He started the 750-piece puzzle Dog Days on Aug. 21, and it took him 12 days to complete it. O'Donnell is a results-only kind of guy who likes to talk about his first puzzle, which took 34 days.",
         "image":"https://backend.offbeat.today/media/tupelo_man_builds_jigsaw_puzzles_to_improve_his_memory.png",
         "newsAgency":"Northeast Mississippi Daily Journal",
         "source":"https://www.djournal.com/lifestyle/tupelo-man-builds-jigsaw-puzzles-to-improve-his-memory/article_5f505951-46cc-5a7e-8cbd-a3d9e80a100f.html",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:06.420144Z",
         "user":null,
         "category":[
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            }
         ],
         "username":null,
         "tags":[
            "aug",
            "days",
            "dog",
            "guy",
            "likes",
            "piece",
            "pieces",
            "talk",
            "took",
            "who"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5819,
         "headline":"Nature's Classroom: The curious art of noticing",
         "time":"2021-01-10T00:00:00Z",
         "body":"The practice of taking some time out and go for a walk can leave you relaxed and rested. The author went on such a walk and shared about his journey. ",
         "image":"https://backend.offbeat.today/media/natures_classroom_the_curious_art_of_noticing.png",
         "newsAgency":"Pueblo Chieftain",
         "source":"https://www.chieftain.com/story/entertainment/2021/01/10/natures-classroom-curious-art-noticing/6552946002/",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:06.243110Z",
         "user":null,
         "category":[
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            }
         ],
         "username":null,
         "tags":[
            "author",
            "journey",
            "leave",
            "practice",
            "shared",
            "taking",
            "time",
            "walk",
            "went"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5818,
         "headline":"JBL Tour Pro+ in-ear headphones offer Adaptive Noise Canceling technology\r\n",
         "time":"2021-01-10T00:00:00Z",
         "body":"The JBL Tour Pro+ in-ear headphones shut out all outside noise. They automatically pair to your android device as soon as you open the case. Dual connect + Sync lets you seamlessly enjoy music or make calls with either one or both buds.",
         "image":"https://backend.offbeat.today/media/jbl_tour_pro_inear_headphones_offer_adaptive_noise_canceling_technology.png",
         "newsAgency":"Gadget Flow",
         "source":"https://thegadgetflow.com/portfolio/jbl-tour-pro-plus-earbuds/",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:06.049243Z",
         "user":null,
         "category":[
            {
               "id":37,
               "name":"Lifestyle",
               "image":"/media/icons8-caretaker-96.png"
            }
         ],
         "username":null,
         "tags":[
            "automatically",
            "dual",
            "ear",
            "lets",
            "music",
            "noise",
            "pair",
            "shut",
            "soon",
            "sync"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5817,
         "headline":"How Phoenix Feeds The Hungry With Fresh Food While Saving Local Businesses and Farms",
         "time":"2021-01-09T00:00:00Z",
         "body":"The city of Phoenix has managed to save dozens of farms and restaurants while getting free meals to those in need. The Feed Phoenix program provided more than 50,000 meals for residents between July and December in 2020. A nonprofit buys produce directly from the farms, then pays the restaurants to prepare and deliver free lunches to the citizens who need it most.",
         "image":"https://backend.offbeat.today/media/how_phoenix_feeds_the_hungry_with_fresh_food_while_saving_local_businesses_and_farms.png",
         "newsAgency":"GoodNewsNetwork",
         "source":"https://www.goodnewsnetwork.org/how-phoenix-feeds-people-and-saves-businesses/",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:05.703341Z",
         "user":null,
         "category":[
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            },
            {
               "id":29,
               "name":"Business",
               "image":"/media/icons8-meeting-96.png"
            },
            {
               "id":39,
               "name":"Food",
               "image":"/media/icons8-hamburger-96.png"
            }
         ],
         "username":null,
         "tags":[
            "city",
            "deliver",
            "feed",
            "free",
            "july",
            "managed",
            "need",
            "prepare",
            "produce",
            "restaurants"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5816,
         "headline":"Love Balenciagas Fall 2021 Armor Boots? Dont Miss This Morgan Library Exhibition About Medieval Fashion",
         "time":"2021-01-10T00:00:00Z",
         "body":"The 2011 exhibition, Illuminating Fashion: Dress in the Art of Medieval France and the Netherlands, is revived online. The show tracks the evolution of fashion from about 1330 to the dawn of the Renaissance, as depicted in illuminated manuscripts.",
         "image":"https://backend.offbeat.today/media/love_balenciagas_fall_2021_armor_boots_dont_miss_this_morgan_library_exhibition_about_me_uFgO6Sz.png",
         "newsAgency":"Vogue.com",
         "source":"https://www.vogue.com/article/medieval-fashion-exhibition-of-illuminated-manuscripts-at-the-morgan-library",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:05.459636Z",
         "user":null,
         "category":[
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            }
         ],
         "username":null,
         "tags":[
            "art",
            "fashion",
            "online",
            "show",
            "tracks"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5815,
         "headline":"How do scientists figure out how old things are?",
         "time":"2021-01-10T00:00:00Z",
         "body":"Radiocarbon dating is the most common method by far, according to experts. It involves measuring quantities of carbon-14, a radioactive carbon isotope or version of an atom with a different number of neutrons. “Everything that's alive takes it up,” says Thomas Higham, an archaeologist at the University of Oxford in England. Uranium-thorium-lead dating allows scientists to measure the age of organic matter",
         "image":"https://backend.offbeat.today/media/how_do_scientists_figure_out_how_old_things_are.png",
         "newsAgency":"Livescience.com",
         "source":"https://www.livescience.com/scientists-dating-methods.html",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:05.231702Z",
         "user":null,
         "category":[
            {
               "id":2,
               "name":"Technology",
               "image":"/media/icons8-bot-128.png"
            },
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            },
            {
               "id":15,
               "name":"Science",
               "image":"/media/icons8-satellites-80.png"
            }
         ],
         "username":null,
         "tags":[
            "according",
            "age",
            "alive",
            "allows",
            "atom",
            "involves",
            "lead",
            "matter",
            "measure",
            "university"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5814,
         "headline":"Australia's SECRET UFO HISTORY: Abductions, disappearances and strange backyard visits\r\n",
         "time":"2021-01-10T00:00:00Z",
         "body":"Despite thousands of sightings across the country over the decades, this is the issue nobody likes to talk about. For many people, it's the first time they have ever talked about it - sometimes decades later, says the host of Australia's secret paranormal podcast Believe, Kade Moir.",
         "image":"https://backend.offbeat.today/media/australias_secret_ufo_history_abductions_disappearances_and_strange_backyard_visits.png",
         "newsAgency":"7NEWS.com.au",
         "source":"https://7news.com.au/lifestyle/offbeat/australias-secret-ufo-history-abductions-disappearances-and-strange-backyard-visits-c-1816105",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:05.045366Z",
         "user":null,
         "category":[
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            }
         ],
         "username":null,
         "tags":[
            "across",
            "believe",
            "country",
            "host",
            "later",
            "likes",
            "people",
            "secret",
            "talk",
            "thousands"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5813,
         "headline":"Holographic startup Envisics partners with Panasonic to fast-track in-car AR tech",
         "time":"2021-01-09T00:00:00Z",
         "body":"The head-up displays will be integrated into the dash of a vehicle. They will project images onto the windshield to aid navigation and provide other alerts. Mass production of vehicles using its technology is slated for 2023, according to the companies.",
         "image":"https://backend.offbeat.today/media/holographic_startup_envisics_partners_with_panasonic_to_fasttrack_incar_ar_tech.png",
         "newsAgency":"TechCrunch",
         "source":"https://techcrunch.com/2021/01/08/holographic-startup-envisics-partners-with-panasonic-to-fast-track-in-car-ar-tech/",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:04.611132Z",
         "user":null,
         "category":[
            {
               "id":2,
               "name":"Technology",
               "image":"/media/icons8-bot-128.png"
            },
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            }
         ],
         "username":null,
         "tags":[
            "alerts",
            "companies",
            "dash",
            "integrated",
            "mass",
            "navigation",
            "production",
            "technology",
            "vehicle",
            "vehicles"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5812,
         "headline":"Warning! Processed foods can cause heart diseases, premature death",
         "time":"2021-01-10T00:00:00Z",
         "body":"Ultra-processed foods with preservatives and added sugar can lead to a higher risk of heart disease. Italian researchers tracked 24,325 men and women aged 35 and above for up to 10 years. 58 percent more likely to die of cardiovascular disease, heart attack, or stroke than those who ate less processed food.",
         "image":"https://backend.offbeat.today/media/warning_processed_foods_can_cause_heart_diseases_premature_death.png",
         "newsAgency":"The Indian Express",
         "source":"https://indianexpress.com/article/lifestyle/health/processed-foods-heart-diseases-premature-death-7140753/",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:04.376235Z",
         "user":null,
         "category":[
            {
               "id":4,
               "name":"World",
               "image":"/media/icons8-world-map-96.png"
            },
            {
               "id":13,
               "name":"Health",
               "image":"/media/icons8-doctor-male-96.png"
            },
            {
               "id":37,
               "name":"Lifestyle",
               "image":"/media/icons8-caretaker-96.png"
            },
            {
               "id":39,
               "name":"Food",
               "image":"/media/icons8-hamburger-96.png"
            }
         ],
         "username":null,
         "tags":[
            "attack",
            "food",
            "heart",
            "lead",
            "likely",
            "percent",
            "processed",
            "risk",
            "stroke",
            "tracked"
         ],
         "save":null,
         "vote":null
      },
      {
         "id":5811,
         "headline":"Nicholas Lazzaro: Education reform and anti-racism resolutions should be implemented",
         "time":"2021-01-10T00:00:00Z",
         "body":"The American education system has been a long-standing form of institutional racism. Eric Liu: the only way we can stomp out racism is through corrective actions. It's more challenging taking note and undo systemic racism.",
         "image":"https://backend.offbeat.today/media/nicholas_lazzaro_education_reform_and_antiracism_resolutions_should_be_implemented.png",
         "newsAgency":"Worcester Telegram",
         "source":"https://www.telegram.com/story/opinion/2021/01/10/nicholas-lazzaro-education-reform-and-anti-racism-resolutions-should-implemented/6591333002/",
         "file_type":"IMG",
         "pos":0,
         "neg":0,
         "clickable":true,
         "visibility":true,
         "independent":false,
         "created_at":"2021-01-12T00:28:04.162102Z",
         "user":null,
         "category":[
            {
               "id":17,
               "name":"Education",
               "image":"/media/icons8-books-96.png"
            }
         ],
         "username":null,
         "tags":[
            "actions",
            "eric",
            "form",
            "long",
            "note",
            "only",
            "system",
            "taking",
            "undo",
            "way"
         ],
         "save":null,
         "vote":null
      }
   ]
};

const ListView = () => {
    const mappedData = data.results.map(ele => {
        return (<ul>
            <li>{ele.id}</li>
            <li>{ele.headline}</li>
            <li>{ele.time}</li>
            <li>{ele.body}</li>
            <li>{ele.image}</li>
            <li>{ele.newsAgency}</li>
            <li>{ele.source}</li>
            <li>{ele.file_type}</li>
            {/* <li>{ele.visibility}</li> */}
            <li>{ele.created_at}</li>
            <br></br>
            <br></br>
        </ul>);
    });
    return <ul>{mappedData}</ul>
}

export default ListView;